# -*- coding: utf-8 -*-
"""task-5-Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJhXKoUAcLTh6sazYwl_TbrYSVUFxcK8

#Importing Libraries
"""

import pandas as pd
from scipy.stats import ttest_ind
import matplotlib.pyplot as plt

"""#Load the dataset"""

df = pd.read_csv("experiment_dataset.csv")

"""#Understanding tha data"""

print(df.info)

print(df.head)

print(df.describe)

"""#caluculation"""

mean_ads = df['total ads'].mean()
median_ads = df['total ads'].median()
mode_ads = df['total ads'].mode()[0]

print("Mean:", mean_ads)
print("Median:", median_ads)
print("Mode:", mode_ads)

df["total ads"].hist()
plt.title("Distribution of Total Ads")
plt.show()

"""#T-test"""

group1 = df[df["test group"]=="ad"]["total ads"]
group2 = df[df["test group"]!="ad"]["total ads"]
t_stat, p_value = ttest_ind(group1, group2)
print("T-statistic:", t_stat)
print("P-value:", p_value)

"""#P-value"""

if p_value < 0.05:
    print("Reject Null Hypothesis")
    print("Groups are significantly different")
else:
    print("Fail to Reject Null Hypothesis")
    print("No significant difference between groups")